### ISSUE TITLE
hidden wifi connection 

### ISSUE THREAD

**Issue by AhmedNabilG** [mocaccinoOS/mocaccino#100]
I'm download gnome iso and kde iso
I'm burn it use dd iso to USB
Boot in live mood
Trying connect to hidden wifi network
But connection failed 
Trying connect to unhidden wifi
The connection working perfect 
Searching for NetworkManager.conf
It's missing on gnome and kde iso

**Comment by joostruis** [comment]
You know the Wifi works because you can connect to a normal visible network. (From conversation on Telegram we know this)
Can you explain what you tried to connect to the hidden network?

**Comment by AhmedNabilG** [comment]
In gnome
Open gnome control
And chose add hidden wifi
Write the wifi name and password
Then connect
But the connection failed
In kde
Open setting
Connection
Chose+
Chose wifi
Edit name and password and chose hidden box
Final connection failed

**Comment by AhmedNabilG** [comment]
But I don't know what are you using for networkmanager backend for trying to fixed it

**Comment by msdobrescu** [comment]
My configs are here: /usr/lib/NetworkManager/
Here is a documentation: https://developer-old.gnome.org/NetworkManager/stable/NetworkManager.conf.html.
We need an error message at least to understand what happens.

**Comment by AhmedNabilG** [comment]
![IMG_20221003_211531_395.jpg](https://user-images.githubusercontent.com/95908703/193660253-ceb290f7-cb5c-4447-89e6-621e5717a39f.jpg)[]()

**Comment by AhmedNabilG** [comment]
I'm sorry my English not good because my language is Arabic
But in all Linux distro I used
NetworkManager.conf
Must be in
/etc/NetworkManager/NetworkManager.conf
It's missing in your distro

**Comment by AhmedNabilG** [comment]
And I'm normal user Not Developer

**Comment by AhmedNabilG** [comment]
I'm sorry I try to fixing it
But I can't
I will go away
Goodbye

**Comment by AhmedNabilG** [comment]
If you're distro based on Gentoo
I think to fix this problem
You need to use 
Use flags
tkip
wifi
Wireless
Networkmanager
I fixed it on another Gentoo based distro

**Comment by willzyx-hub** [comment]
tkip use flags are disabled since Gentoo decide to deprecate TKIP so wifi network using TKIP will not work out of the box.

**Comment by joostruis** [comment]
@willzyx-hub thanks for explaining this. So do you think we should enable this flag or would that cause potential security issues? That flag should be enabled on wpa_supplicant AFAIK

**Comment by willzyx-hub** [comment]
> @willzyx-hub thanks for explaining this. So do you think we should enable this flag or would that cause potential security issues? That flag should be enabled on wpa_supplicant AFAIK

I don't know how to enable it on mocaccinoOS

**Comment by joostruis** [comment]
I know how and where to enable it. Question is if we should.
