### ISSUE TITLE
easy desktop envireoment switchinh.

### ISSUE THREAD

**Issue by justAguy321** [mocaccinoOS/mocaccino#101]
easy was to switch from default to other installed enviroments like plasma/elagance/cinnamon...ect

**Describe alternatives you've considered**
like many other distros maybe put in logout/in screen?

**Comment by joostruis** [comment]
Not sure what DM you are using but you are able to switch between different Desktop Environments. Perhaps you did not find the button to do this? In GDM you must first fill in a username, then you have an option to choose the desktop env.
