### ISSUE TITLE
Software app on gnome has nothing in explore.

### ISSUE THREAD

**Issue by justAguy321** [mocaccinoOS/mocaccino#102]
OS ver / latest
GNOME ver 42,4

**Comment by joostruis** [comment]
Hello.
To be clear. There is NO integration with GNOME Software and Luet PackageManager. You can configure GNOME Software to browse software on flathub. To do so, as mentionted in documentation, you need to enable flathub first.

`flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo`

Also see: https://www.mocaccino.org/docs/desktop/flatpak/
