### ISSUE TITLE
Mocaccino images to use as an LXC container in proxmox

### ISSUE THREAD

**Issue by r1k0** [mocaccinoOS/mocaccino#106]
**Is your feature request related to a problem? Please describe.**

I would like to install mocaccino as an LXC container in proxmox.

**Describe the solution you'd like**

I would like to download the archive from the github repo (next to ISOs).

**Describe alternatives you've considered**

I would like to follow a guide to build myself a mocaccino archive I can use as an LXC container in proxmox.

**Additional context**

No additional context. Many thanks for all the work, It's a great and very interesting project.

**Comment by joostruis** [comment]
Closing this.
