### ISSUE TITLE
some weird glitches on logon screen 

### ISSUE THREAD

**Issue by theunclemez** [mocaccinoOS/mocaccino#11]
no comment, just look at logon screen
this is weird and do happen on each session opening

![Screenshot_mocaccino_2021-05-30_00:26:55](https://user-images.githubusercontent.com/50036470/120087314-af39b700-c0de-11eb-84d3-a62d37407efa.png)

**Comment by geaaru** [comment]
This is related to the `/etc/motd` created by mocaccino skel package. It's needed rename `/etc/motd` in `/etc/issue` and exclude it from layer/system-x.

**Comment by mudler** [comment]
Or, just find out why gdm wants to display the motd so badly there.

**Comment by mudler** [comment]
JFYI: https://bbs.archlinux.org/viewtopic.php?id=180217

**Comment by joostruis** [comment]
This is solved now.
