### ISSUE TITLE
Issue with steam and some other apps "window opening and closing right away"

### ISSUE THREAD

**Issue by fgn-itsupport** [mocaccinoOS/mocaccino#115]
**Luet version:**
luet version 0.32.5-gd5d21653d7313ff396c0511af402834c89974ee3 2022-06-07

**CPU architecture, OS, and Version:**
Dell Latitude 3420
Linux mostest 5.15.63-mocaccino #5.15.63-Mocaccino SMP Fri Aug 26 20:50:33 UTC 2022 x86_64 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz GenuineIntel GNU/Linux

Lenovo T460
Linux minkas-linux 5.15.72-mocaccino #5.15.72-Mocaccino SMP Tue Oct 11 13:47:20 UTC 2022 x86_64 Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz GenuineIntel GNU/Linux

**Describe the bug**
Window opens and closes right away
This does happen with other applications like aetherium as well or openra

**To Reproduce**
luet install apps/steam
open steam
install game
starting game

**Expected behavior**
Steam app/games should work and the opening window should stay open. 

**Logs**
Dell Latitude 3420
Nov 15 19:03:09 mostest steam.desktop[24575]: GameAction [AppID 32360, ActionID 3] : LaunchApp changed task to ProcessingInstallScript with ""
Nov 15 19:03:09 mostest steam.desktop[24575]: GameAction [AppID 32360, ActionID 3] : LaunchApp changed task to SynchronizingCloud with ""
Nov 15 19:03:10 mostest steam.desktop[24575]: GameAction [AppID 32360, ActionID 3] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
Nov 15 19:03:10 mostest steam.desktop[24575]: GameAction [AppID 32360, ActionID 3] : LaunchApp changed task to CreatingProcess with ""
Nov 15 19:03:10 mostest steam.desktop[24575]: GameAction [AppID 32360, ActionID 3] : LaunchApp waiting for user response to CreatingProcess ""
Nov 15 19:03:10 mostest steam.desktop[24575]: GameAction [AppID 32360, ActionID 3] : LaunchApp continues with user response "CreatingProcess"
Nov 15 19:03:10 mostest steam.desktop[24575]: /bin/sh\0-c\0/home/crusader/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=32360 -- /home/crusader/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/home/crusader/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier'/_v2-entry-point --verb=waitforexitandrun -- '/home/crusader/.local/share/Steam/steamapps/common/Proton - Experimental'/proton waitforexitandrun  '/home/crusader/.local/share/Steam/steamapps/common/The Secret of Monkey Island Special Edition/MISE.exe'\0
Nov 15 19:03:10 mostest steam.desktop[24575]: Game process added : AppID 32360 "/home/crusader/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=32360 -- /home/crusader/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/home/crusader/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier'/_v2-entry-point --verb=waitforexitandrun -- '/home/crusader/.local/share/Steam/steamapps/common/Proton - Experimental'/proton waitforexitandrun  '/home/crusader/.local/share/Steam/steamapps/common/The Secret of Monkey Island Special Edition/MISE.exe'", ProcID 25845, IP 0.0.0.0:0
Nov 15 19:03:10 mostest steam.desktop[25845]: ERROR: ld.so: object '/home/crusader/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Nov 15 19:03:10 mostest steam.desktop[24575]: GameAction [AppID 32360, ActionID 3] : LaunchApp changed task to WaitingGameWindow with ""
Nov 15 19:03:10 mostest steam.desktop[25845]: ERROR: ld.so: object '/home/crusader/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
Nov 15 19:03:10 mostest steam.desktop[25846]: ERROR: ld.so: object '/home/crusader/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Nov 15 19:03:10 mostest steam.desktop[24575]: GameAction [AppID 32360, ActionID 3] : LaunchApp changed task to Completed with ""
Nov 15 19:03:10 mostest steam.desktop[25846]: ERROR: ld.so: object '/home/crusader/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Nov 15 19:03:10 mostest steam.desktop[25846]: ERROR: ld.so: object '/home/crusader/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Nov 15 19:03:10 mostest steam.desktop[25847]: ERROR: ld.so: object '/home/crusader/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
Nov 15 19:03:10 mostest steam.desktop[25849]: pid 25849 != 25846, skipping destruction (fork without exec?)
Nov 15 19:03:11 mostest steam.desktop[25955]: esync: up and running.
Nov 15 19:03:11 mostest steam.desktop[25955]: wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
Nov 15 19:03:11 mostest steam.desktop[24575]: ThreadGetProcessExitCode: no such process 25954
Nov 15 19:03:11 mostest steam.desktop[24575]: ThreadGetProcessExitCode: no such process 25952
Nov 15 19:03:11 mostest steam.desktop[24575]: ThreadGetProcessExitCode: no such process 25951
Nov 15 19:03:11 mostest steam.desktop[24575]: ThreadGetProcessExitCode: no such process 25950
Nov 15 19:03:11 mostest steam.desktop[24575]: ThreadGetProcessExitCode: no such process 25847
Nov 15 19:03:12 mostest steam.desktop[24575]: Game process updated : AppID 32360 "/home/crusader/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=32360 -- /home/crusader/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/home/crusader/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier'/_v2-entry-point --verb=waitforexitandrun -- '/home/crusader/.local/share/Steam/steamapps/common/Proton - Experimental'/proton waitforexitandrun  '/home/crusader/.local/share/Steam/steamapps/common/The Secret of Monkey Island Special Edition/MISE.exe'", ProcID 25953, IP 0.0.0.0:0
Nov 15 19:03:12 mostest steam.desktop[25953]: Setting breakpad minidump AppID = 32360
Nov 15 19:03:12 mostest steam.desktop[25953]: Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198049858172 [API loaded no]
Nov 15 19:03:12 mostest steam.desktop[25998]: MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0
Nov 15 19:03:12 mostest steam.desktop[24575]: ThreadGetProcessExitCode: no such process 25957
Nov 15 19:03:13 mostest steam.desktop[24575]: Game process updated : AppID 32360 "/home/crusader/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=32360 -- /home/crusader/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/home/crusader/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier'/_v2-entry-point --verb=waitforexitandrun -- '/home/crusader/.local/share/Steam/steamapps/common/Proton - Experimental'/proton waitforexitandrun  '/home/crusader/.local/share/Steam/steamapps/common/The Secret of Monkey Island Special Edition/MISE.exe'", ProcID 26027, IP 0.0.0.0:0
Nov 15 19:03:13 mostest steam.desktop[26027]: MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0
Nov 15 19:03:13 mostest steam.desktop[26027]: Fossilize INFO: Overriding serialization path: "/home/crusader/.local/share/Steam/steamapps/shadercache/32360/fozpipelinesv6/steamapprun_pipeline_cache".
Nov 15 19:03:13 mostest gnome-shell[1606]: Window manager warning: Window 0x3200001 sets an MWM hint indicating it isn't resizable, but sets min size 1 x 1 and max size 2147483647 x 2147483647; this doesn't make much sense.
Nov 15 19:03:13 mostest steam.desktop[26027]: wine: Unhandled page fault on read access to 00000000 at address 00481C8C (thread 0134), starting debugger...
Nov 15 19:03:13 mostest steam.desktop[26041]: Unhandled exception: page fault on read access to 0x00000000 in 32-bit code (0x00481c8c).
Nov 15 19:03:13 mostest steam.desktop[26041]: Register dump:
Nov 15 19:03:13 mostest steam.desktop[26041]:  CS:0023 SS:002b DS:002b ES:002b FS:0063 GS:006b
Nov 15 19:03:13 mostest steam.desktop[26041]:  EIP:00481c8c ESP:0881fd18 EBP:00000000 EFLAGS:00210206(  R- --  I   - -P- )
Nov 15 19:03:13 mostest steam.desktop[26041]:  EAX:00000000 EBX:80004005 ECX:0881fd3c EDX:004f0bac
Nov 15 19:03:13 mostest steam.desktop[26041]:  ESI:03797c80 EDI:00000000
Nov 15 19:03:13 mostest steam.desktop[26041]: Stack dump:
Nov 15 19:03:13 mostest steam.desktop[26041]: 0x0881fd18:  00000000 0881fe90 80004005 00000000
Nov 15 19:03:13 mostest steam.desktop[26041]: 0x0881fd28:  00ae4930 073c0020 0045bc7c 0881fdd4
Nov 15 19:03:13 mostest steam.desktop[26041]: 0x0881fd38:  0881fd5c 00000000 00000000 00000000
Nov 15 19:03:13 mostest steam.desktop[26041]: 0x0881fd48:  00000000 003e2000 00000301 00000134
Nov 15 19:03:13 mostest steam.desktop[26041]: 0x0881fd58:  0881fd7c 0881fe90 00000000 80004005
Nov 15 19:03:13 mostest steam.desktop[26041]: 0x0881fd68:  0046e3b1 00000040 00481c03 00000000
Nov 15 19:03:13 mostest steam.desktop[26041]: Backtrace:
Nov 15 19:03:13 mostest steam.desktop[26041]: =>0 0x00481c8c in mise (+0x81c8c) (0x00000000)
Nov 15 19:03:13 mostest steam.desktop[26041]: 0x00481c8c mise+0x81c8c: movl        0x0(%eax),%edx
Nov 15 19:03:13 mostest steam.desktop[26041]: Modules:
Nov 15 19:03:13 mostest steam.desktop[26041]: Module        Address                        Debug info        Name (34 modules)
Nov 15 19:03:13 mostest steam.desktop[26041]: PE        00140000-0019a000        Deferred        combase
Nov 15 19:03:13 mostest steam.desktop[26041]: PE        00400000-00622000        Export          mise
Nov 15 19:03:13 mostest steam.desktop[26041]: PE        06ad0000-06b00000        Deferred        winevulkan
Nov 15 19:03:13 mostest steam.desktop[26041]: PE        61740000-61784000        Deferred        advapi32
Nov 15 19:03:13 mostest steam.desktop[26041]: PE        62440000-62775000        Deferred        d3d9
Nov 15 19:03:13 mostest steam.desktop[26041]: PE        62fc0000-6304e000        Deferred        rpcrt4
Nov 15 19:03:13 mostest steam.desktop[26041]: PE        63480000-6348d000        Deferred        version
Nov 15 19:03:13 mostest steam.desktop[26041]: PE        63bc0000-63bda000        Deferred        shcore
Nov 15 19:03:13 mostest steam.desktop[26041]: PE        64a40000-64a94000        Deferred        shlwapi
Nov 15 19:03:13 mostest steam.desktop[26041]: PE        651c0000-651d3000        Deferred        xinput1_3
Nov 15 19:03:13 mostest steam.desktop[26041]: PE        666c0000-666cf000        Deferred        hid
Nov 15 19:03:13 mostest steam.desktop[26041]: PE        66880000-66997000        Deferred        msvcp80
Nov 15 19:03:13 mostest steam.desktop[26041]: PE        66b00000-66b3e000        Deferred        win32u
Nov 15 19:03:13 mostest steam.desktop[26041]: PE        67a00000-67a2d000        Deferred        d3dxof
Nov 15 19:03:13 mostest steam.desktop[26041]: PE        67ec0000-687fa000        Deferred        shell32
Nov 15 19:03:13 mostest steam.desktop[26041]: PE        69ac0000-69acd000        Deferred        vulkan-1
Nov 15 19:03:13 mostest steam.desktop[26041]: PE        69d80000-69dd4000        Deferred        d3dcompiler_47
Nov 15 19:03:13 mostest steam.desktop[26041]: PE        6a280000-6a32e000        Deferred        msvcrt
Nov 15 19:03:13 mostest steam.desktop[26041]: PE        6a400000-6a533000        Deferred        ole32
Nov 15 19:03:13 mostest steam.desktop[26041]: PE        6b100000-6b10c000        Deferred        x3daudio1_6
Nov 15 19:03:13 mostest steam.desktop[26041]: PE        6b840000-6b8f8000        Deferred        msvcr80
Nov 15 19:03:13 mostest steam.desktop[26041]: PE        6bc00000-6bc2c000        Deferred        sechost
Nov 15 19:03:13 mostest steam.desktop[26041]: PE        6bcc0000-6bd41000        Deferred        setupapi
Nov 15 19:03:13 mostest steam.desktop[26041]: PE        6bdc0000-6be6a000        Deferred        d3dx9_41
Nov 15 19:03:13 mostest steam.desktop[26041]: PE        6c9c0000-6ca45000        Deferred        gdi32
Nov 15 19:03:13 mostest steam.desktop[26041]: PE        6df80000-6e018000        Deferred        libvkd3d-shader-1
Nov 15 19:03:13 mostest steam.desktop[26041]: PE        6ed00000-6ef41000        Deferred        user32
Nov 15 19:03:13 mostest steam.desktop[26041]: PE        70b40000-70c1c000        Deferred        ucrtbase
Nov 15 19:03:13 mostest steam.desktop[26041]: PE        71200000-7121c000        Deferred        imm32
Nov 15 19:03:13 mostest steam.desktop[26041]: PE        7b000000-7b0ef000        Deferred        kernelbase
Nov 15 19:03:13 mostest steam.desktop[26041]: PE        7b600000-7b81a000        Deferred        kernel32
Nov 15 19:03:13 mostest steam.desktop[26041]: PE        7bc00000-7bca8000        Deferred        ntdll
Nov 15 19:03:13 mostest steam.desktop[26041]: PE        f3b50000-f3b54000        Deferred        winex11
Nov 15 19:03:13 mostest steam.desktop[26041]: PE        f5e30000-f5e33000        Deferred        lsteamclient
Nov 15 19:03:13 mostest steam.desktop[26041]: Threads:
Nov 15 19:03:13 mostest steam.desktop[26041]: process  tid      prio (all id:s are in hex)
Nov 15 19:03:13 mostest steam.desktop[26041]: 00000020 steam.exe
Nov 15 19:03:13 mostest steam.desktop[26041]:         00000024    0
Nov 15 19:03:13 mostest steam.desktop[26041]:         000000c0    0
Nov 15 19:03:13 mostest steam.desktop[26041]:         0000013c    0
Nov 15 19:03:13 mostest steam.desktop[26041]: 00000030 services.exe
Nov 15 19:03:13 mostest steam.desktop[26041]:         00000034    0
Nov 15 19:03:13 mostest steam.desktop[26041]:         00000038    0
Nov 15 19:03:13 mostest steam.desktop[26041]:         00000044    0
Nov 15 19:03:13 mostest steam.desktop[26041]:         00000048    0
Nov 15 19:03:13 mostest steam.desktop[26041]:         00000054    0
Nov 15 19:03:13 mostest steam.desktop[26041]:         00000068    0
Nov 15 19:03:13 mostest steam.desktop[26041]:         00000074    0
Nov 15 19:03:13 mostest steam.desktop[26041]:         00000098    0
Nov 15 19:03:13 mostest steam.desktop[26041]:         000000b0    0
Nov 15 19:03:13 mostest steam.desktop[26041]:         000000f0    0
Nov 15 19:03:13 mostest steam.desktop[26041]:         000000f4    0
Nov 15 19:03:13 mostest steam.desktop[26041]:         000000f8    0
Nov 15 19:03:13 mostest steam.desktop[26041]: 0000003c winedevice.exe
Nov 15 19:03:13 mostest steam.desktop[26041]:         00000040    0
Nov 15 19:03:13 mostest steam.desktop[26041]:         0000004c    0
Nov 15 19:03:13 mostest steam.desktop[26041]:         00000050    0
Nov 15 19:03:13 mostest steam.desktop[26041]:         00000058    0
Nov 15 19:03:13 mostest steam.desktop[26041]:         0000005c    0
Nov 15 19:03:13 mostest steam.desktop[26041]:         000000bc    0
Nov 15 19:03:13 mostest steam.desktop[26041]: 00000060 winedevice.exe
Nov 15 19:03:13 mostest steam.desktop[26041]:         00000064    0
Nov 15 19:03:13 mostest steam.desktop[26041]:         0000006c    0
Nov 15 19:03:13 mostest steam.desktop[26041]:         00000070    0
Nov 15 19:03:13 mostest steam.desktop[26041]:         00000078    0
Nov 15 19:03:13 mostest steam.desktop[26041]:         0000007c    0
Nov 15 19:03:13 mostest steam.desktop[26041]:         00000080    0
Nov 15 19:03:13 mostest steam.desktop[26041]:         00000084    0
Nov 15 19:03:13 mostest steam.desktop[26041]:         0000008c    0
Nov 15 19:03:13 mostest steam.desktop[26041]: 00000090 plugplay.exe
Nov 15 19:03:13 mostest steam.desktop[26041]:         00000094    0
Nov 15 19:03:13 mostest steam.desktop[26041]:         0000009c    0
Nov 15 19:03:13 mostest steam.desktop[26041]:         000000a0    0
Nov 15 19:03:13 mostest steam.desktop[26041]:         000000a4    0
Nov 15 19:03:13 mostest steam.desktop[26041]: 000000a8 svchost.exe
Nov 15 19:03:13 mostest steam.desktop[26041]:         000000ac    0
Nov 15 19:03:13 mostest steam.desktop[26041]:         000000b4    0
Nov 15 19:03:13 mostest steam.desktop[26041]:         000000b8    0
Nov 15 19:03:13 mostest steam.desktop[26041]: 000000c4 explorer.exe
Nov 15 19:03:13 mostest steam.desktop[26041]:         000000c8    0
Nov 15 19:03:13 mostest steam.desktop[26041]:         000000d4    0
Nov 15 19:03:13 mostest steam.desktop[26041]:         000000d8    0
Nov 15 19:03:13 mostest steam.desktop[26041]: 000000e0 rpcss.exe
Nov 15 19:03:13 mostest steam.desktop[26041]:         000000e4    0
Nov 15 19:03:13 mostest steam.desktop[26041]:         000000fc    0
Nov 15 19:03:13 mostest steam.desktop[26041]:         00000100    0
Nov 15 19:03:13 mostest steam.desktop[26041]:         00000104    0
Nov 15 19:03:13 mostest steam.desktop[26041]:         00000108    0
Nov 15 19:03:13 mostest steam.desktop[26041]:         0000010c    0
Nov 15 19:03:13 mostest steam.desktop[26041]:         00000110    0
Nov 15 19:03:13 mostest steam.desktop[26041]: 00000118 tabtip.exe
Nov 15 19:03:13 mostest steam.desktop[26041]:         0000011c    0
Nov 15 19:03:13 mostest steam.desktop[26041]:         0000012c    0
Nov 15 19:03:13 mostest steam.desktop[26041]:         00000138    0
Nov 15 19:03:13 mostest steam.desktop[26041]: 00000130 (D) Z:\home\crusader\.local\share\Steam\steamapps\common\The Secret of Monkey Island Special Edition\MISE.exe
Nov 15 19:03:13 mostest steam.desktop[26041]:         00000134    0 <==
Nov 15 19:03:13 mostest steam.desktop[26041]:         00000140    0
Nov 15 19:03:13 mostest steam.desktop[26041]:         00000144    0
Nov 15 19:03:13 mostest steam.desktop[26041]:         00000148    1
Nov 15 19:03:13 mostest steam.desktop[26041]:         0000014c    0
Nov 15 19:03:13 mostest steam.desktop[26041]:         00000150    0
Nov 15 19:03:13 mostest steam.desktop[26041]:         00000154    0
Nov 15 19:03:13 mostest steam.desktop[26041]:         00000160    0
Nov 15 19:03:13 mostest steam.desktop[26041]: System information:
Nov 15 19:03:13 mostest steam.desktop[26041]:     Wine build: wine-7.0
Nov 15 19:03:13 mostest steam.desktop[26041]:     Platform: i386 (WOW64)
Nov 15 19:03:13 mostest steam.desktop[26041]:     Version: Windows 10
Nov 15 19:03:13 mostest steam.desktop[26041]:     Host system: Linux
Nov 15 19:03:13 mostest steam.desktop[26041]:     Host version: 5.15.63-mocaccino
Nov 15 19:03:13 mostest steam.desktop[24575]: ThreadGetProcessExitCode: no such process 26041
Nov 15 19:03:13 mostest steam.desktop[24575]: ThreadGetProcessExitCode: no such process 25962
Nov 15 19:03:13 mostest steam.desktop[25955]: pid 25955 != 25954, skipping destruction (fork without exec?)
Nov 15 19:03:14 mostest steam.desktop[24575]: Game process removed: AppID 32360 "/home/crusader/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=32360 -- /home/crusader/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/home/crusader/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier'/_v2-entry-point --verb=waitforexitandrun -- '/home/crusader/.local/share/Steam/steamapps/common/Proton - Experimental'/proton waitforexitandrun  '/home/crusader/.local/share/Steam/steamapps/common/The Secret of Monkey Island Special Edition/MISE.exe'", ProcID 26027
Nov 15 19:03:14 mostest steam.desktop[24575]: ThreadGetProcessExitCode: no such process 26027
Nov 15 19:03:14 mostest steam.desktop[24575]: ThreadGetProcessExitCode: no such process 26007
Nov 15 19:03:14 mostest steam.desktop[24575]: ThreadGetProcessExitCode: no such process 25991
Nov 15 19:03:14 mostest steam.desktop[24575]: ThreadGetProcessExitCode: no such process 25985
Nov 15 19:03:14 mostest steam.desktop[24575]: ThreadGetProcessExitCode: no such process 25971
Nov 15 19:03:14 mostest steam.desktop[24575]: ThreadGetProcessExitCode: no such process 25959
Nov 15 19:03:14 mostest steam.desktop[24575]: ThreadGetProcessExitCode: no such process 25953
Nov 15 19:03:14 mostest steam.desktop[24575]: ThreadGetProcessExitCode: no such process 25948
Nov 15 19:03:14 mostest steam.desktop[24575]: ThreadGetProcessExitCode: no such process 25846
Nov 15 19:03:14 mostest steam.desktop[24575]: Game 32360 created interface STEAMAPPS_INTERFACE_VERSION003 / Apps
Nov 15 19:03:14 mostest steam.desktop[24575]: Game 32360 created interface SteamUtils004 / Utils
Nov 15 19:03:14 mostest steam.desktop[24575]: Game 32360 method call count for IClientAppManager::BIsDlcEnabled : 1
Nov 15 19:03:14 mostest steam.desktop[24575]: Game 32360 method call count for IClientUtils::RecordSteamInterfaceCreation : 2
Nov 15 19:03:14 mostest steam.desktop[24575]: Game 32360 method call count for IClientUtils::GetAppID : 3
Nov 15 19:03:14 mostest steam.desktop[24575]: Game 32360 method call count for IClientUser::BIsSubscribedApp : 1
Nov 15 19:03:14 mostest steam.desktop[24575]: Uploaded AppInterfaceStats to Steam

**Additional context**
Hardware: 
Dell Latitude 3420
glxinfo | grep render
direct rendering: Yes
    GLX_MESA_query_renderer, GLX_MESA_swap_control, GLX_NV_float_buffer, 
    GLX_MESA_query_renderer, GLX_MESA_swap_control, GLX_OML_swap_method, 
Extended renderer info (GLX_MESA_query_renderer):
OpenGL renderer string: Mesa Intel(R) Xe Graphics (TGL GT2)
    GL_ARB_compute_variable_group_size, GL_ARB_conditional_render_inverted, 
    GL_IBM_multimode_draw_arrays, GL_INTEL_blackhole_render, 
    GL_NV_conditional_render, GL_NV_copy_image, GL_NV_depth_clamp, 
    GL_ARB_compute_variable_group_size, GL_ARB_conditional_render_inverted, 
    GL_INTEL_blackhole_render, GL_INTEL_performance_query, 
    GL_NV_compute_shader_derivatives, GL_NV_conditional_render, 
    GL_EXT_render_snorm, GL_EXT_robustness, GL_EXT_sRGB_write_control, 
    GL_EXT_unpack_subimage, GL_INTEL_blackhole_render, 
    GL_NV_compute_shader_derivatives, GL_NV_conditional_render, 
    GL_OES_element_index_uint, GL_OES_fbo_render_mipmap,

lspci|grep VGA
0000:00:02.0 VGA compatible controller: Intel Corporation TigerLake-LP GT2 [Iris Xe Graphics] (rev 01)

Lenovo T460
glxinfo |grep render
direct rendering: Yes
    GLX_MESA_query_renderer, GLX_MESA_swap_control, GLX_NV_float_buffer, 
    GLX_MESA_query_renderer, GLX_MESA_swap_control, GLX_OML_swap_method, 
Extended renderer info (GLX_MESA_query_renderer):
OpenGL renderer string: Mesa Intel(R) HD Graphics 520 (SKL GT2)
    GL_ARB_compute_variable_group_size, GL_ARB_conditional_render_inverted, 
    GL_IBM_multimode_draw_arrays, GL_INTEL_blackhole_render, 
    GL_NV_conditional_render, GL_NV_copy_image, GL_NV_depth_clamp, 
    GL_ARB_compute_variable_group_size, GL_ARB_conditional_render_inverted, 
    GL_INTEL_blackhole_render, GL_INTEL_performance_query, 
    GL_NV_compute_shader_derivatives, GL_NV_conditional_render, 
    GL_EXT_render_snorm, GL_EXT_robustness, GL_EXT_sRGB_write_control, 
    GL_EXT_unpack_subimage, GL_INTEL_blackhole_render, 
    GL_NV_compute_shader_derivatives, GL_NV_conditional_render, 
    GL_OES_element_index_uint, GL_OES_fbo_render_mipmap,

lspci |grep VGA
00:02.0 VGA compatible controller: Intel Corporation Skylake GT2 [HD Graphics 520] (rev 07)

**Comment by joostruis** [comment]
I can not reproduce this. I did a fresh install of MOS desktop KDE. 
Installed apps/steam -> works fine.
Installed openra from flathub --> works fine.

`joost-30ces0k600 /home/joost # lspci | grep VGA
00:02.0 VGA compatible controller: Intel Corporation CoffeeLake-S GT2 [UHD Graphics 630]
`

**Comment by fgn-itsupport** [comment]
Sorry it wasn't OpenRA which failed, I mixed that up. It was Bombermaaan. 
Aside from that, Steam itself works fine, enable the advanced gameing support so it uses Proton and try to run a Proton based windows game. I tried The secret of Monkey Island. Starting that fails right away. I can search for other apps which are failing, cause there have been more, but I don't remember which one anymore.

**Comment by lashomb** [comment]
Bombermaaan works fine for me, on MOS desktop KDE. Installed from flathub.

**Comment by fgn-itsupport** [comment]
Strange, cause I have two different systems, one Dell and one Lenovo, and both do have the same behaviour. What else could it be?

**Comment by joostruis** [comment]
Issue is upstream. If you read e.g. comments on flathub about Bombermaaan users from several distros report it broken.
