### ISSUE TITLE
bash completion missing

### ISSUE THREAD

**Issue by theunclemez** [mocaccinoOS/mocaccino#12]
tested and installed,
but completion is missing in terminal
but please, keep the output coloring and please bring some output in table mode at least for stuffs like upgrade/update

**Comment by joostruis** [comment]
bash-completion has been available before this issue was reported. 
https://github.com/mocaccinoOS/desktop/commit/6a31aa7959e508cf30b51eb2abf4e36346cb0ab8#diff-ffb649d60333b6e420cbc24fa71eba1b5ee58af7c0a4d000cf22d92a2f8c4a9d

Can you please explain what you mean?

**Comment by joostruis** [comment]
`xbox-360 /home/joost/mocaccino/desktop # l
Display all 190 possibilities? (y or n)
`
I am closing this.
