### ISSUE TITLE
no wifi on one machine

### ISSUE THREAD

**Issue by yusssufff** [mocaccinoOS/mocaccino#121]
hi!
I have no wifi on one machine.

Here is result from live-usb of another distro (gentoo based calculate-linux)

guest@calculate ~ $ lspci
00:00.0 Host bridge: Intel Corporation 2nd Generation Core Processor Family DRAM Controller (rev 09)
00:01.0 PCI bridge: Intel Corporation Xeon E3-1200/2nd Generation Core Processor Family PCI Express Root Port (rev 09)
00:01.1 PCI bridge: Intel Corporation Xeon E3-1200/2nd Generation Core Processor Family PCI Express Root Port (rev 09)
00:01.2 PCI bridge: Intel Corporation Xeon E3-1200/2nd Generation Core Processor Family PCI Express Root Port (rev 09)
00:02.0 VGA compatible controller: Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller (rev 09)
00:16.0 Communication controller: Intel Corporation 6 Series/C200 Series Chipset Family MEI Controller #1 (rev 04)
00:1a.0 USB controller: Intel Corporation 6 Series/C200 Series Chipset Family USB Enhanced Host Controller #2 (rev 04)
00:1b.0 Audio device: Intel Corporation 6 Series/C200 Series Chipset Family High Definition Audio Controller (rev 04)
00:1c.0 PCI bridge: Intel Corporation 6 Series/C200 Series Chipset Family PCI Express Root Port 1 (rev b4)
00:1c.1 PCI bridge: Intel Corporation 6 Series/C200 Series Chipset Family PCI Express Root Port 2 (rev b4)
00:1c.2 PCI bridge: Intel Corporation 6 Series/C200 Series Chipset Family PCI Express Root Port 3 (rev b4)
00:1d.0 USB controller: Intel Corporation 6 Series/C200 Series Chipset Family USB Enhanced Host Controller #1 (rev 04)
00:1f.0 ISA bridge: Intel Corporation HM65 Express Chipset LPC Controller (rev 04)
00:1f.2 SATA controller: Intel Corporation 6 Series/C200 Series Chipset Family 6 port Mobile SATA AHCI Controller (rev 04)
00:1f.3 SMBus: Intel Corporation 6 Series/C200 Series Chipset Family SMBus Controller (rev 04)
01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Seymour [Radeon HD 6400M/7400M Series]
04:00.0 Network controller: Broadcom Inc. and subsidiaries BCM4313 802.11bgn Wireless Network Adapter (rev 01)
05:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL810xE PCI Express Fast Ethernet controller (rev 05)
06:00.0 Unassigned class [ff00]: Realtek Semiconductor Co., Ltd. RTS5209 PCI Express Card Reader (rev 01)

guest@calculate ~ $ lsmod | tail -n +2 | cut -f 1 -d ' ' | xargs modinfo -F firmware
brcm/bcm43xx_hdr-0.fw
brcm/bcm43xx-0.fw
b43/ucode9.fw
b43/ucode42.fw
b43/ucode40.fw
b43/ucode5.fw
b43/ucode30_mimo.fw
b43/ucode33_lcn40.fw
b43/ucode29_mimo.fw
b43/ucode26_mimo.fw
b43/ucode25_mimo.fw
b43/ucode25_lcn.fw
b43/ucode24_lcn.fw
b43/ucode16_mimo.fw
b43/ucode16_lp.fw
b43/ucode15.fw
b43/ucode14.fw
b43/ucode13.fw
b43/ucode11.fw
mediatek/mt7668pr2h.bin
mediatek/mt7663pr2h.bin
rtl_bt/rtl8852au_config.bin
rtl_bt/rtl8852au_fw.bin
rtl_bt/rtl8822b_config.bin
rtl_bt/rtl8822b_fw.bin
rtl_bt/rtl8821a_config.bin
rtl_bt/rtl8821a_fw.bin
rtl_bt/rtl8761a_config.bin
rtl_bt/rtl8761a_fw.bin
rtl_bt/rtl8723ds_config.bin
rtl_bt/rtl8723ds_fw.bin
rtl_bt/rtl8723bs_config.bin
rtl_bt/rtl8723bs_fw.bin
rtl_bt/rtl8723b_config.bin
rtl_bt/rtl8723b_fw.bin
rtl_bt/rtl8723a_fw.bin
intel/ibt-12-16.ddc
intel/ibt-12-16.sfi
intel/ibt-11-5.ddc
intel/ibt-11-5.sfi
regulatory.db
regulatory.db.p7s
rtl_nic/rtl8125b-2.fw
rtl_nic/rtl8125a-3.fw
rtl_nic/rtl8107e-2.fw
rtl_nic/rtl8107e-1.fw
rtl_nic/rtl8168fp-3.fw
rtl_nic/rtl8168h-2.fw
rtl_nic/rtl8168h-1.fw
rtl_nic/rtl8168g-3.fw
rtl_nic/rtl8168g-2.fw
rtl_nic/rtl8106e-2.fw
rtl_nic/rtl8106e-1.fw
rtl_nic/rtl8411-2.fw
rtl_nic/rtl8411-1.fw
rtl_nic/rtl8402-1.fw
rtl_nic/rtl8168f-2.fw
rtl_nic/rtl8168f-1.fw
rtl_nic/rtl8105e-1.fw
rtl_nic/rtl8168e-3.fw
rtl_nic/rtl8168e-2.fw
rtl_nic/rtl8168e-1.fw
rtl_nic/rtl8168d-2.fw
rtl_nic/rtl8168d-1.fw
i915/skl_huc_2.0.0.bin
i915/skl_guc_62.0.0.bin
i915/bxt_huc_2.0.0.bin
i915/bxt_guc_62.0.0.bin
i915/kbl_huc_4.0.0.bin
i915/kbl_guc_62.0.0.bin
i915/glk_huc_4.0.0.bin
i915/glk_guc_62.0.0.bin
i915/kbl_huc_4.0.0.bin
i915/kbl_guc_62.0.0.bin
i915/kbl_huc_4.0.0.bin
i915/kbl_guc_62.0.0.bin
i915/cml_huc_4.0.0.bin
i915/cml_guc_62.0.0.bin
i915/icl_huc_9.0.0.bin
i915/icl_guc_62.0.0.bin
i915/ehl_huc_9.0.0.bin
i915/ehl_guc_62.0.0.bin
i915/ehl_huc_9.0.0.bin
i915/ehl_guc_62.0.0.bin
i915/tgl_huc_7.9.3.bin
i915/tgl_guc_62.0.0.bin
i915/tgl_huc_7.9.3.bin
i915/tgl_guc_62.0.0.bin
i915/tgl_huc_7.9.3.bin
i915/tgl_guc_62.0.0.bin
i915/tgl_huc_7.9.3.bin
i915/adlp_guc_62.0.3.bin
i915/bxt_dmc_ver1_07.bin
i915/skl_dmc_ver1_27.bin
i915/kbl_dmc_ver1_04.bin
i915/glk_dmc_ver1_04.bin
i915/icl_dmc_ver1_09.bin
i915/tgl_dmc_ver2_12.bin
i915/rkl_dmc_ver2_03.bin
i915/dg1_dmc_ver2_02.bin
i915/adls_dmc_ver2_01.bin
i915/adlp_dmc_ver2_10.bin
radeon/R520_cp.bin
radeon/RS600_cp.bin
radeon/RS690_cp.bin
radeon/R420_cp.bin
radeon/R300_cp.bin
radeon/R200_cp.bin
radeon/R100_cp.bin
radeon/SUMO2_me.bin
radeon/SUMO2_pfp.bin
radeon/SUMO_me.bin
radeon/SUMO_pfp.bin
radeon/SUMO_rlc.bin
radeon/PALM_me.bin
radeon/PALM_pfp.bin
radeon/CYPRESS_smc.bin
radeon/CYPRESS_rlc.bin
radeon/CYPRESS_me.bin
radeon/CYPRESS_pfp.bin
radeon/JUNIPER_smc.bin
radeon/JUNIPER_rlc.bin
radeon/JUNIPER_me.bin
radeon/JUNIPER_pfp.bin
radeon/REDWOOD_smc.bin
radeon/REDWOOD_rlc.bin
radeon/REDWOOD_me.bin
radeon/REDWOOD_pfp.bin
radeon/CEDAR_smc.bin
radeon/CEDAR_rlc.bin
radeon/CEDAR_me.bin
radeon/CEDAR_pfp.bin
radeon/R700_rlc.bin
radeon/R600_rlc.bin
radeon/RV710_smc.bin
radeon/RV710_me.bin
radeon/RV710_pfp.bin
radeon/RV740_smc.bin
radeon/RV730_smc.bin
radeon/RV730_me.bin
radeon/RV730_pfp.bin
radeon/RV770_smc.bin
radeon/RV770_me.bin
radeon/RV770_pfp.bin
radeon/RS780_me.bin
radeon/RS780_pfp.bin
radeon/RV670_me.bin
radeon/RV670_pfp.bin
radeon/RV635_me.bin
radeon/RV635_pfp.bin
radeon/RV620_me.bin
radeon/RV620_pfp.bin
radeon/RV630_me.bin
radeon/RV630_pfp.bin
radeon/RV610_me.bin
radeon/RV610_pfp.bin
radeon/R600_me.bin
radeon/R600_pfp.bin
radeon/ARUBA_rlc.bin
radeon/ARUBA_me.bin
radeon/ARUBA_pfp.bin
radeon/CAYMAN_smc.bin
radeon/CAYMAN_rlc.bin
radeon/CAYMAN_mc.bin
radeon/CAYMAN_me.bin
radeon/CAYMAN_pfp.bin
radeon/CAICOS_smc.bin
radeon/CAICOS_mc.bin
radeon/CAICOS_me.bin
radeon/CAICOS_pfp.bin
radeon/TURKS_smc.bin
radeon/TURKS_mc.bin
radeon/TURKS_me.bin
radeon/TURKS_pfp.bin
radeon/BTC_rlc.bin
radeon/BARTS_smc.bin
radeon/BARTS_mc.bin
radeon/BARTS_me.bin
radeon/BARTS_pfp.bin
radeon/si58_mc.bin
radeon/banks_k_2_smc.bin
radeon/hainan_k_smc.bin
radeon/hainan_smc.bin
radeon/hainan_rlc.bin
radeon/hainan_mc.bin
radeon/hainan_ce.bin
radeon/hainan_me.bin
radeon/hainan_pfp.bin
radeon/HAINAN_smc.bin
radeon/HAINAN_rlc.bin
radeon/HAINAN_mc2.bin
radeon/HAINAN_mc.bin
radeon/HAINAN_ce.bin
radeon/HAINAN_me.bin
radeon/HAINAN_pfp.bin
radeon/oland_k_smc.bin
radeon/oland_smc.bin
radeon/oland_rlc.bin
radeon/oland_mc.bin
radeon/oland_ce.bin
radeon/oland_me.bin
radeon/oland_pfp.bin
radeon/OLAND_smc.bin
radeon/OLAND_rlc.bin
radeon/OLAND_mc2.bin
radeon/OLAND_mc.bin
radeon/OLAND_ce.bin
radeon/OLAND_me.bin
radeon/OLAND_pfp.bin
radeon/verde_k_smc.bin
radeon/verde_smc.bin
radeon/verde_rlc.bin
radeon/verde_mc.bin
radeon/verde_ce.bin
radeon/verde_me.bin
radeon/verde_pfp.bin
radeon/VERDE_smc.bin
radeon/VERDE_rlc.bin
radeon/VERDE_mc2.bin
radeon/VERDE_mc.bin
radeon/VERDE_ce.bin
radeon/VERDE_me.bin
radeon/VERDE_pfp.bin
radeon/pitcairn_k_smc.bin
radeon/pitcairn_smc.bin
radeon/pitcairn_rlc.bin
radeon/pitcairn_mc.bin
radeon/pitcairn_ce.bin
radeon/pitcairn_me.bin
radeon/pitcairn_pfp.bin
radeon/PITCAIRN_smc.bin
radeon/PITCAIRN_rlc.bin
radeon/PITCAIRN_mc2.bin
radeon/PITCAIRN_mc.bin
radeon/PITCAIRN_ce.bin
radeon/PITCAIRN_me.bin
radeon/PITCAIRN_pfp.bin
radeon/tahiti_smc.bin
radeon/tahiti_rlc.bin
radeon/tahiti_mc.bin
radeon/tahiti_ce.bin
radeon/tahiti_me.bin
radeon/tahiti_pfp.bin
radeon/TAHITI_smc.bin
radeon/TAHITI_rlc.bin
radeon/TAHITI_mc2.bin
radeon/TAHITI_mc.bin
radeon/TAHITI_ce.bin
radeon/TAHITI_me.bin
radeon/TAHITI_pfp.bin
radeon/mullins_sdma.bin
radeon/mullins_rlc.bin
radeon/mullins_mec.bin
radeon/mullins_ce.bin
radeon/mullins_me.bin
radeon/mullins_pfp.bin
radeon/MULLINS_sdma.bin
radeon/MULLINS_rlc.bin
radeon/MULLINS_mec.bin
radeon/MULLINS_ce.bin
radeon/MULLINS_me.bin
radeon/MULLINS_pfp.bin
radeon/kabini_sdma.bin
radeon/kabini_rlc.bin
radeon/kabini_mec.bin
radeon/kabini_ce.bin
radeon/kabini_me.bin
radeon/kabini_pfp.bin
radeon/KABINI_sdma.bin
radeon/KABINI_rlc.bin
radeon/KABINI_mec.bin
radeon/KABINI_ce.bin
radeon/KABINI_me.bin
radeon/KABINI_pfp.bin
radeon/kaveri_sdma.bin
radeon/kaveri_rlc.bin
radeon/kaveri_mec2.bin
radeon/kaveri_mec.bin
radeon/kaveri_ce.bin
radeon/kaveri_me.bin
radeon/kaveri_pfp.bin
radeon/KAVERI_sdma.bin
radeon/KAVERI_rlc.bin
radeon/KAVERI_mec.bin
radeon/KAVERI_ce.bin
radeon/KAVERI_me.bin
radeon/KAVERI_pfp.bin
radeon/hawaii_k_smc.bin
radeon/hawaii_smc.bin
radeon/hawaii_sdma.bin
radeon/hawaii_rlc.bin
radeon/hawaii_mc.bin
radeon/hawaii_mec.bin
radeon/hawaii_ce.bin
radeon/hawaii_me.bin
radeon/hawaii_pfp.bin
radeon/HAWAII_smc.bin
radeon/HAWAII_sdma.bin
radeon/HAWAII_rlc.bin
radeon/HAWAII_mc2.bin
radeon/HAWAII_mc.bin
radeon/HAWAII_mec.bin
radeon/HAWAII_ce.bin
radeon/HAWAII_me.bin
radeon/HAWAII_pfp.bin
radeon/bonaire_k_smc.bin
radeon/bonaire_smc.bin
radeon/bonaire_sdma.bin
radeon/bonaire_rlc.bin
radeon/bonaire_mc.bin
radeon/bonaire_mec.bin
radeon/bonaire_ce.bin
radeon/bonaire_me.bin
radeon/bonaire_pfp.bin
radeon/BONAIRE_smc.bin
radeon/BONAIRE_sdma.bin
radeon/BONAIRE_rlc.bin
radeon/BONAIRE_mc2.bin
radeon/BONAIRE_mc.bin
radeon/BONAIRE_mec.bin
radeon/BONAIRE_ce.bin
radeon/BONAIRE_me.bin
radeon/BONAIRE_pfp.bin
radeon/bonaire_uvd.bin
radeon/BONAIRE_uvd.bin
radeon/TAHITI_uvd.bin
radeon/SUMO_uvd.bin
radeon/CYPRESS_uvd.bin
radeon/RV710_uvd.bin
radeon/RV770_uvd.bin
radeon/RS780_uvd.bin
radeon/R600_uvd.bin
radeon/BONAIRE_vce.bin
radeon/TAHITI_vce.bin
cxgb4/t6fw.bin
cxgb4/t5fw.bin
cxgb4/t4fw.bin
cxgb3/ael2020_twx_edc.bin
cxgb3/ael2005_twx_edc.bin
cxgb3/ael2005_opt_edc.bin
cxgb3/t3c_psram-1.1.0.bin
cxgb3/t3b_psram-1.1.0.bin
cxgb3/t3fw-7.12.0.bin

**Comment by joostruis** [comment]
Hi there and thanks for your report. 
I think the missing firmware files you require are provided in layers/firmware-brcm
Can you try installing layers/firmware-brcm and see if that resolves your problem?

**Comment by joostruis** [comment]
You could try one of these devel images. 
https://github.com/mocaccinoOS/mocaccino/actions/runs/4190038840

Only to confirm Wifi works on it on live session. (I do not recommend installing a development iso)

**Comment by joostruis** [comment]
Issue resolved by adding missing firmware.
