### ISSUE TITLE
firefox:rapid

### ISSUE THREAD

**Issue by yusssufff** [mocaccinoOS/mocaccino#124]
Maybe i misunderstand the Gentoo Wiki, but it seems adding ''~amd64 keyword'' when compiling from stable tree would bring a more fresh (non esr, or ''rapid'') version.
''To install Firefox from source:
root #emerge --ask www-client/firefox
This will install Firefox Extended Support Release (ESR) on a stable branch Gentoo system (or Firefox "Rapid release" if ~amd64 keyword is selected).  ''

from: https://wiki.gentoo.org/wiki/Firefox

**Comment by joostruis** [comment]
Hello there. We strictly follow the Gentoo stable tree. So I am not going to add this "rapid" version.
