### ISSUE TITLE
closing the terminal during luet upgrade breaks kernel

### ISSUE THREAD

**Issue by yusssufff** [mocaccinoOS/mocaccino#126]
Hi!

So yes as title said, i just closed the terminal during a luet upgrade.
I am aware that this is not the best use case, but that may happen to anyone.
So the thing is that after reboot there is Kernel panic and no kernel found.
I guess that is connected to MOS not keeping any "backup" kernel?

I think the design of MOS as quite solid is great.
But how do we make the upgrade a bit more solid so that closing the terminal doesn't end in Kernel Panic?

**Comment by msdobrescu** [comment]
I would not have restarted, but opened another console and reissued the upgrade/update.
I would fix the setup by booting a live ISO, chrooting and continuing the process, alternately reinstalling the kernel.

**Comment by joostruis** [comment]
I would not call this an issue rather an user error. That also would have been fixable if you chrooted in and repaired.
