### ISSUE TITLE
error installing virtualbox-guest-additions-lts and virtualbox-modules-lts

### ISSUE THREAD

**Issue by cain071546** [mocaccinoOS/mocaccino#129]
**Luet version:**

"MocaccinoOS --version" returns bash: MocaccinoOS: command not found

**CPU architecture, OS, and Version:**

Linux cain-virtualbox 6.1.35-mocaccino #6.1.35-Mocaccino SMP PREEMPT_DYNAMIC Sat June 24 09:08:32 UTC 20 x86_64 AMD Ryzen 5 5600 6-Core Processor AuthenticAMD GNU/Linux

**Describe the bug**

running "luet install virtualbox virtualbox-modules-lts virtualbox-guest-additions-lts
or any of the three packages independently.

returns : Error: Failed matching solutions against repository for virtualbox where are definitions coming from?!

**To Reproduce**

Install any of the three packages virtualbox, virtualbox-modules-lts, virtualbox-guest-additions-lts
**Expected behavior**

**Logs**

**Additional context**

I have no clue, totally new package manager to me, seems rather intuitive though and I've been browsing available documentation but to no avail.

**Comment by msdobrescu** [comment]
Hi, it's `luet --version`, not `MocaccinoOS --version`.

When managing packages, the category must be provided also, meaning:

`luet install apps/virtualbox`
