### ISSUE TITLE
Cannot import VPN connection

### ISSUE THREAD

**Issue by ghost** [mocaccinoOS/mocaccino#13]
**CPU architecture, OS, and Version:**

Linux Lenovo-G50-45 5.10.35-mocaccino #5.10.35-Mocaccino SMP Sat May 8 07:35:17 UTC 2021 x86_64  AMD A6-6310 APU with AMD Radeon R4 Graphics AuthenticAMD GNU/Linux

**Describe the bug**

I can't import any VPN configuration file.

**To Reproduce**

https://i.postimg.cc/W39kT7kX/Screenshot-from-2021-05-31-23-25-51.png
https://i.postimg.cc/d1QybfLh/Screenshot-from-2021-05-31-23-26-07.png

**Additional context**

I've installed each of the packages named "VPN" in the repos but there's no change in behaviour.

**Comment by joostruis** [comment]
Can we close this?
