### ISSUE TITLE
Still does not running 

### ISSUE THREAD

**Issue by Ygarr** [mocaccinoOS/mocaccino#131]
Even in Qemu.
Qemu run command
sudo qemu-system-x86_64 -cpu host -boot menu=on -drive file=qemu-x86_64.qcow2,format=qcow2 -vga <virtio/qxl> -display gtk -m 8G -enable-kvm  -boot d -cdrom "MocaccinoOS-XFCE-0.20230707.iso" -smp 4

**Comment by joostruis** [comment]
Closing this due lack of feedback.
