### ISSUE TITLE
provide fish in the repos

### ISSUE THREAD

**Issue by PiotrBajdek** [mocaccinoOS/mocaccino#14]
**Describe the solution you'd like**

Please, provide the fish shell in the repos.

**Additional context**

https://fishshell.com/

**Comment by joostruis** [comment]
I think you want to open your issues here https://github.com/mocaccinoOS/desktop/issues

**Comment by mudler** [comment]
> I think you want to open your issues here https://github.com/mocaccinoOS/desktop/issues

no, here it's fine. That's our external tracker and where the website directly opens the issues to

**Comment by joostruis** [comment]
Will be available soon as apps/fish
