### ISSUE TITLE
provide inxi

### ISSUE THREAD

**Issue by PiotrBajdek** [mocaccinoOS/mocaccino#16]
**Describe the solution you'd like**

Please, provide inxi in the repos.

**Additional context**

It's a very useful tool and just standard in any Linux distro.

**Comment by joostruis** [comment]
We could provide a gazillion scripts on certain layers but I wonder why we should. Download the Perl script from upstream and run it as you like?

**Comment by PiotrBajdek** [comment]
Thanks, Joost. I made it work:
`cd /usr/local/bin && wget -O inxi smxi.org/inxi && chmod +x inxi`

And I'm sorry--this is the first disto in my life which doesn't provide it by default. I've never used neither Sabayon nor Gentoo.
