### ISSUE TITLE
No Keyboard on Acer Chromebook 14 (Intel Braswell and Celeron N3160)

### ISSUE THREAD

**Issue by cAptive5976** [mocaccinoOS/mocaccino#2]
I tested a lot of Linux distribution and I found mocaccino which had a rather interesting functioning. But like few Gentoo (except ChromeOS) and "From Scratch" distros do not have the functional keyboard. If you know where this bug comes from can you fix it or tell me how to fix it please ?

**Comment by joostruis** [comment]
Could you tell me if this is an issue that is still in latest beta images?

**Comment by joostruis** [comment]
closing
