### ISSUE TITLE
Unlocked TTYs after install

### ISSUE THREAD

**Issue by jcfrosty** [mocaccinoOS/mocaccino#20]
After fresh install of Mocaccino-Gnome I checked the other TTYs and it appears ALL the TTYs are unlocked and logged in as root. Having open root terminals in all TTYs is not secure.

**Comment by msdobrescu** [comment]
Which ISO (stable/dev)? A version from July 17th did not have this issue. I still have the install.

**Comment by msdobrescu** [comment]
I have downloaded and installed MocaccinoOS-GNOME-dev-0.20210725.iso, I can't reproduce the issue.

**Comment by joostruis** [comment]
Can't reproduce here.
