### ISSUE TITLE
cannot install gcc-base, server returns 404

### ISSUE THREAD

**Issue by EdgarCarpenter** [mocaccinoOS/mocaccino#23]
**Luet version:**

fluet version 0.17.2-gdb8bf2b85e6802f843dfe8c863beb6e28e8e4e5f 2021-07-30 01:28:34 UTC

**CPU architecture, OS, and Version:**

Linux EdgarNUC 5.13.1-mocaccino #5.13.1-Mocaccino SMP Wed Jul 14 17:08:18 UTC 2021 x86_64 Intel(R) Core(TM) i7-8809G CPU @ 3.10GHz GenuineIntel GNU/Linux

**Describe the bug**

gcc-base is required for packages I want to install - Krusader and Thunderbird.  Those installs fail with 404 from the server because gcc-base is missing. 

When I try to install gcc-base explicitly, it also fails with 404

**To Reproduce**

[aaa@EdgarNUC ~]$ sudo luet install system/gcc-base
I get:
 Packages that are going to be installed in the system: 
  gcc-base-system-10.3.0+9 (mocaccino-desktop)

then:
 Failed downloading package gcc-base Error on download artifact: server returned 404 Not Found

When I say:
[aaa@EdgarNUC ~]$ sudo luet search gcc-base
I get:
--- Search results (gcc-base): ---
 ╭─ system/gcc-base-10.3.0+9
│  ├─ Category: system
│  ├─ Name: gcc-base
│  ├─ Version: 10.3.0+9
│  ├─ Description: 
│  ├─ Repository: mocaccino-desktop 
│  ╰─ Uri:  
╰─ system/gcc-base-10.3.0+4
   ├─ Category: system
   ├─ Name: gcc-base
   ├─ Version: 10.3.0+4
   ├─ Description: 
   ├─ Repository: mocaccino-desktop-stable 
   ╰─ Uri:  

**Expected behavior**

gcc-base should install. 

**Logs**

**Additional context**

I am new to mocaccino, this is an initial install. 

Thanks for your help - carpen@panix.com

**Comment by mudler** [comment]
Thanks for opening the issue!

Looks like you installed a -development versions. It is shipping development repositories, so that's expected. I would suggest you to switch to stable instead.

**Comment by msdobrescu** [comment]
This occurred to me too regardless the -dev or -stable, when using Gnome ISO only.

**Comment by mudler** [comment]
> This occurred to me too regardless the -dev or -stable, when using Gnome ISO only.

Can you check the repository enabled in such case?

**Comment by msdobrescu** [comment]
Not sure, i have had this issue once during testing the ISOs, I must re-install them, but I can not right now until we conclude https://github.com/mudler/luet/issues/237.
