### ISSUE TITLE
Plymouth errors in journal due to deprecated option in use

### ISSUE THREAD

**Issue by jcfrosty** [mocaccinoOS/mocaccino#34]
Aug 08 16:38:36 Zero systemd[1]: /lib/systemd/system/plymouth-start.service:15: Unit configured to use KillMode=none. This is unsafe, as it disables systemd's process lifecycle management for the service. Please update your service to use a safer KillMode=, such as 'mixed' or 'control-group'. Support for KillMode=none is deprecated and will eventually be removed.

**Comment by joostruis** [comment]
Relevant patch is here:
https://cgit.freedesktop.org/plymouth/commit/systemd-units/plymouth-start.service.in?id=9d0f8b2e7bc2d1d2b0900fcdf119bb9a2cc4f474
Upstream Gentoo has not touched Plymouth for years.  What are we going to do about this?

**Comment by joostruis** [comment]
`sed '/^sConditionVirtualization.*/a IgnoreOnIsolate=true' /lib/systemd/system/plymouth-start.service
sed -i -e 's/KillMode=none/KillMode=mixed/g' /lib/systemd/system/plymouth-start.service`
