### ISSUE TITLE
Error when trying to install software

### ISSUE THREAD

**Issue by okchaimike62** [mocaccinoOS/mocaccino#54]
**Luet version:**
<-luet version 0.22.3-g57eedf8e7ef60632b883fffbc0d0aac0d923fef1 2021-12-28->

**CPU architecture, OS, and Version:**
<Linux mike-optiplex3020 5.10.49-mocaccino #5.10.49-Mocaccino SMP Thu Jul 15 08:40:00 UTC 2021 x86_64 Intel(R) Core(TM) i3-4150 CPU @ 3.50GHz GenuineIntel GNU/Linux>

**Describe the bug**
< when i try to install a piece of software (luet install firefox for example),  the system looks like it is trying to do another upgrade. it gives a list of software to install and if you select "yes", it throws out this error 

"INFO   By going forward, you are also accepting the licenses of the packages that you are going to install in your system.
 INFO   Do you want to continue with this operation? [y/N]: y
 INFO   Checking for file conflicts..
  ERROR    Error: file conflict found: file conflict between packages to be installed">

**To Reproduce**
<"luet install (package)" >

**Expected behavior**
< I expected that when i ran "luet install (package)" the system would install only the packages specified>

**Logs**

**Additional context**

**Comment by royalpenguin64** [comment]
If it helps, I attach my test reporters.
I state that I left Mate, it as it was in conflict with the kernel, after the first `luet upgrade`. It doesn't happen with Gnome.

```
 WARNING   failed downloading image quay.io/mocaccino/kernel-stable:mocaccino-lts-modules-kernel-5.10.82: Get "https://quay.io/v2/": dial tcp: i/o timeout
panic: runtime error: invalid memory address or nil pointer dereference         
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x13e7314]
```

```
[test-1.txt](https://github.com/mocaccinoOS/mocaccino/files/7816211/test-1.txt)

INFO   Checking for file conflicts..
  ERROR    Error: while checking upgrades before install: file conflict found: file conflict between packages to be installed
``
[test-1.txt](https://github.com/mocaccinoOS/mocaccino/files/7816217/test-1.txt)
[test-2.txt](https://github.com/mocaccinoOS/mocaccino/files/7816220/test-2.txt)
`

**Comment by royalpenguin64** [comment]
If it helps, I attach my 3th test reporter.

```
ERROR    Error: 1 error occurred:
          	* Failed running command: update-mime-database: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory
          : exit status 127
```

[test3.txt](https://github.com/mocaccinoOS/mocaccino/files/7835587/test3.txt)
