### ISSUE TITLE
Mocaccino OS Mate Beta issue after install

### ISSUE THREAD

**Issue by okchaimike62** [mocaccinoOS/mocaccino#59]
**Luet version:**
<0.22.7>

**CPU architecture, OS, and Version:**
< AMD Ryzen 5 3600 (12) @ 3.6GHz, Mocaccino OS Beta (Mate)>

**Describe the bug**
<failure to start network manager upon boot after install and reboot>

**To Reproduce**
<attempted to make USB install drives with several different pieces of software (etcher, popsicle, etc.>

**Expected behavior**
<after installing from USB, system should continue booting>

**Logs**

**Additional context**

**Comment by mudler** [comment]
@okchaimike62 thanks for the report! can you tell how does far it gets to boot? can you give any screenshot? does it tries to boot into the live environment?

**Comment by okchaimike62** [comment]
Good Morning mudler!,  this happens after an install right before the desktop should appear. I will get you a screenshot ASAP
thanks!

**Comment by okchaimike62** [comment]
Good Morning Ettore, here is what I have as far as screen shots. The system
never makes it to the desktop. After the "network manager" error, it dumps
to a command line prompt and goes no further. I noticed that if you 'ls' at
the prompt the only thing shown is the Desktop. I tried all versions of the
beta and noticed on the KDE version, it also gives a SDDM error as well as
on the Gnome version also.  I hope this helps. I use Arch linux quite a bit
but I am always looking for new and interesting OS options!

thanks again
Mike

**Comment by joostruis** [comment]
Can you boot any other Linux on that machine and run this:

`lsmod | tail -n +2 | cut -f 1 -d ' ' | xargs modinfo -F firmware`

And if that returns any data share it with us?

would also be nice if you could provide us with the output of  `lspci`

Thanks.

**Comment by okchaimike62** [comment]
sure thing, here ya go

**Comment by joostruis** [comment]
I am looking here but can't see your attachments?

https://github.com/mocaccinoOS/mocaccino/issues/59

**Comment by okchaimike62** [comment]
sorry, try this....
[lsmod for Mocaccino diagnostics.odt](https://github.com/mocaccinoOS/mocaccino/files/8310026/lsmod.for.Mocaccino.diagnostics.odt)
[lspci for Mocaccino diagnostics.odt](https://github.com/mocaccinoOS/mocaccino/files/8310027/lspci.for.Mocaccino.diagnostics.odt)

**Comment by joostruis** [comment]
@okchaimike62 I found in your log that your system (the one that works) is using firmware from amd that we did not yet include. I changed this in the commit above. As I write this I am generating test iso images that will include this. It would be very interesting to see if this actually fixes the problem.

**Comment by joostruis** [comment]
@okchaimike62 If you scroll down on this page:
https://github.com/mocaccinoOS/mocaccino/actions/runs/2007287469

You see "artifacts" generated. There you see the test iso images. Would be great if you could test one of these!

**Comment by okchaimike62** [comment]
sure, I'm always happy to try new operating systems!

**Comment by joostruis** [comment]
Since I suspect your issue has to do with missing firmware and meanwhile fixed some other issues I already released an updated beta.

https://github.com/mocaccinoOS/mocaccino/releases/tag/v0.1.0-beta01

So no need to grab those -dev iso images I posted earlier.

**Comment by okchaimike62** [comment]
Ok thanks, I'm in the process of downloading the new beta. I will let you
know what the outcome is.

thanks again

**Comment by joostruis** [comment]
@jcfrosty see above. Could you help test btrfs install? To my knowledge this should work but apparently there is an issue.

**Comment by okchaimike62** [comment]
joostruis, i will continue to run the OS through it's paces and trying btrfs installs also. i will let you know if i come across something.

**Comment by joostruis** [comment]
Closing this.
