### ISSUE TITLE
gnome-shell works faster after awakening up from sleeping mode

### ISSUE THREAD

**Issue by constantius24** [mocaccinoOS/mocaccino#68]
**Luet version:**
0.31.2

**CPU architecture, OS, and Version:**
5.15.35 but 5.15.32 was the same bug

**Describe the bug**
 after fresh boot gnome-shell works slowly eat 30-100% cpu depend on software running. After put computer Gnome in sleep mode and awakening gnome-shell works much more faster. Please see into https://github.com/mocaccinoOS/mocaccino/discussions/67

**To Reproduce**

**Expected behavior**

**Logs**

**Additional context**

**Comment by joostruis** [comment]
That is a bit hard to work with as you might understand. 
First off all. Could you post your system specs?

**Comment by constantius24** [comment]
The last luet 0.31.2. kernel 5.15.35 x86-64amd. Gnome 41.4 nvidia gt710 properiaty legacy driver , xorg, which log file do you need?

**Comment by constantius24** [comment]
I wonder if it is cause i did migration from sabayon to moccacino without format root and home directory... But its only suspect

**Comment by constantius24** [comment]
I have changed Nvidia properiaty driver to nvidia-drivers-lts  from legacy and I set all the graphics card settings in nvidia-settings to maximum openGL performance, and enhance application settings 32X, override application settings 16x, and I was able to greatly minimize the slowness of the gnome-shell. But the phenomenon does occur. Maybe this is some Gnome bug 40 and above. I have manjaro on another computer but it doesn't occur.

**Comment by joostruis** [comment]
> I wonder if it is cause i did migration from sabayon to moccacino without format root and home directory... But its only suspect

That could be the issue yes.

With system specs I mean what is your hardware? (CPU, GPU, RAM, etc)

But please when you try to help test, do a CLEAN install.

**Comment by joostruis** [comment]
closing
