### ISSUE TITLE
Luet kernel-switcher Removes Core Packages

### ISSUE THREAD

**Issue by akelling** [mocaccinoOS/mocaccino#7]
Luet version: sharp-standardpci440fxpiix1996 ~ # luet --version
luet version 0.14.1-g946524f90de7c4c9f579749f868b91f5f58f5750 2021-04-24 07:17:36 UTC

CPU architecture, OS, and Version: sharp@sharp-standardpci440fxpiix1996 ~ $ uname -a
Linux sharp-standardpci440fxpiix1996 5.10.31-mocaccino #5.10.31-Mocaccino SMP Tue Apr 20 16:11:08 UTC 2021 x86_64 AMD Opteron 62xx class CPU AuthenticAMD GNU/Linux

**Describe the bug**
Running the following command removes core system packages
' luet kernel-switcher list'

**To Reproduce**
Run the command listed above.

**Expected behavior**
Not to remove core packages and to list kernel packages like the old kernel-switcher

**Logs**
transcript of my logs have been attached
[luet_bug.txt](https://github.com/mocaccinoOS/mocaccino/files/6387506/luet_bug.txt)

**Comment by mudler** [comment]
Switching kernels for now has been tested only on Micro, and the docs is really strict about it, there is no such "list" command either. 

https://www.mocaccino.org/docs/micro/kernels/ 

But I do see the issue here, actually, `kernel-switcher` should be moved around the `mos` CLI

**Comment by akelling** [comment]
@mudler I totally understand where you are coming from but its more the issue that if there is an unexpected sub command removing all the system files in this case.

**Comment by mudler** [comment]
Luet kernel-switcher will be deprecated soon, see https://www.mocaccino.org/docs/general/kernels/ on how to switch kernels, it's still in development but that should cover what `luet kernel-switcher` is providing now ( plus the ability to list kernels )
