### ISSUE TITLE
Latte-dock install issue in Beta 4

### ISSUE THREAD

**Issue by okchaimike62** [mocaccinoOS/mocaccino#79]
**Luet version:**
<luet version 0.32.0-g2aa4c8a42ed13682b4820f3ca5e6d2388a5e2c24 2022-05-03
>

**CPU architecture, OS, and Version:**
<Linux RyzenBeastCLX 5.15.38-mocaccino #5.15.38-Mocaccino SMP Fri May 13 15:51:02 UTC 2022 x86_64 AMD Ryzen 5 3600 6-Core Processor AuthenticAMD GNU/Linux
>

**Describe the bug**
<fatal error after attempting to install latte-dock>

**To Reproduce**
<luet install apps/latte-dock>

**Expected behavior**
<successful install without error>

**Logs**

**Additional context**
<RyzenBeastCLX /home/mike # luet install apps/latte-dock
 INFO  Luet 0.32.0-g2aa4c8a42ed13682b4820f3ca5e6d2388a5e2c24 2022-05-03
 INFO  Copyright (C) 2019-2022 Ettore Di Giacinto
       This program comes with ABSOLUTELY NO WARRANTY.
       This is free software, and you are welcome to redistribute it under certain conditions.
       For documentation, visit https://luet.io.
 INFO   :::> Install
 INFO   Downloading quay.io/mocaccino/mocaccino-community:repository.yaml
 INFO   Pulled: sha256:3130955bae35ede5343996e0da04bc453893b9fbf57f46f7a94dedbb0f060716
 INFO   Size: 634B
 INFO   Downloading quay.io/mocaccino/mocaccino-community:tree.tar.gz
 INFO   Pulled: sha256:1f25e0803dadbc2ced5131b7bdb260c583fe7d1117a1449bae915cd5acfb8382
 INFO   Size: 81.7KiB
 INFO   Downloading quay.io/mocaccino/mocaccino-community:repository.meta.yaml.tar
 INFO   Pulled: sha256:17c46aaf8a02c308e6f5116e5054ba07c7925d882474ae3e71acf8fc2500beaa
 INFO   Size: 9.207MiB
 INFO   🏠  Repository mocaccino-community revision: 506 (2022-05-15 13:16:06 -0500 CDT)
 INFO   ℹ  Repository: mocaccino-community Priority: 50 Type: docker
 INFO   🤔  Checking for available upgrades
 INFO   Nothing to upgrade
 INFO   Packages that are going to be installed in the system:

Program Name             | Version  | License | Repository
apps/latte-dock-3.1.2+27 | 3.1.2+27 |         | mocaccino-community

 INFO   By going forward, you are also accepting the licenses of the packages that you are going to install in your system.
 INFO   Do you want to continue with this operation? [y/N]:
y
 INFO   Checking for file conflicts..
 INFO   Done checking for file conflicts..
 INFO   📦  Package  apps/latte-dock-3.1.2+27 installed
 WARNING   Failed rendering finalizer for  apps/latte-dock-3.1.2+27 template: :1:12: executing "" at <{{template "finalize" .}}>: template "finalize" not defined
  ERROR    Error: 1 error occurred:
                * template: :1:12: executing "" at <{{template "finalize" .}}>: template "finalize" not defined
panic: fatal error

goroutine 1 [running]:
github.com/mudler/luet/pkg/api/core/logger.(*Logger).Fatal(...)
        /luetbuild/luet/pkg/api/core/logger/logger.go:255
github.com/mudler/luet/cmd.glob..func10(0x162a8c0?, {0xc00049ae50?, 0x1?, 0x1?})
        /luetbuild/luet/cmd/install.go:94 +0x5c5
github.com/spf13/cobra.(*Command).execute(0x162a8c0, {0xc00049ae20, 0x1, 0x1})
        /luetbuild/luet/vendor/github.com/spf13/cobra/command.go:860 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0x1628ac0)
        /luetbuild/luet/vendor/github.com/spf13/cobra/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        /luetbuild/luet/vendor/github.com/spf13/cobra/command.go:902
github.com/mudler/luet/cmd.Execute()
        /luetbuild/luet/cmd/root.go:124 +0x25
main.main()
        /luetbuild/luet/main.go:10 +0x17
>

**Comment by msdobrescu** [comment]
@okchaimike62, this is [community repo](https://github.com/mocaccinoOS/community-repository) issue and will be addressed ASAP.

**Comment by msdobrescu** [comment]
Solved, please check by issuing:

`luet reinstall apps/latte-dock`

That's because the package is installed, but failed to finalize, meaning to run:

```
update-mime-database /usr/share/mime/
ldconfig

```

**Comment by okchaimike62** [comment]
ok, actually i tried that last nite with no luck (or at least i thought i did) but after trying again this morning, it worked with no issues? sorry for the false alarm guys...latte-dock installed and functional....thanks
