### ISSUE TITLE
Enable MocaccinoOS Visibility in Repology

### ISSUE THREAD

**Issue by chrisdebian** [mocaccinoOS/mocaccino#85]
[Repology](https://repology.org/) is a well known site, where users and developers can gain a quick understanding of packages in a distro. This includes potential vulnerabilities, package version numbers, and many more options.

Could the Mocaccino developers please consider being listed on this website, more information can be found [here](https://repology.org/docs/requirements)

Many thanks,

Chris
chris_debian | 2E0FRU

**Comment by joostruis** [comment]
closing
