### ISSUE TITLE
No WebP support out of the box

### ISSUE THREAD

**Issue by jcfrosty** [mocaccinoOS/mocaccino#95]
Fresh install of Gnome image, cannot open webp images. This means applications are missing the webp use flag.

**Comment by joostruis** [comment]
Seems that the above change did not yet fix the issue. 
Might be an upstream bug still.

https://bugs.gentoo.org/703866
https://bugs.gentoo.org/849380

**Comment by joostruis** [comment]
![image](https://user-images.githubusercontent.com/1949179/195999608-9da6451c-5b09-40f0-8003-cb7c345fb23e.png)
Works for me now.
